name: Build and Release Electron App

on:
  push:
    tags:
      - 'v*'   # Ex: v1.0.0
  workflow_dispatch:

jobs:
  build:
    name: Build Electron App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      # 1️⃣ Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      # 3️⃣ Installer pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # 4️⃣ Installer les dépendances
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 5️⃣ Builder le frontend (Vite)
      - name: Build frontend
        run: pnpm build

      # 6️⃣ Builder Electron
      - name: Package Electron app
        run: pnpm dist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # 🧩 important pour publier sur GitHub
          CSC_LINK: ${{ secrets.CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_APP_PASSWORD: ${{ secrets.APPLE_APP_PASSWORD }}

      # 7️⃣ Uploader les builds comme artefacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-build
          path: release/

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build

    steps:
      # 8️⃣ Télécharger les artefacts créés par les builds
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: release-assets

      # 9️⃣ Créer la Release GitHub + attacher les fichiers
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}     # 🔥 important pour prendre le tag poussé
          name: Release ${{ github.ref_name }}
          files: release-assets/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
